// ====================================================================
// מאגר מוצרים כשרים ביוון — מחולץ אך ורק משני המסמכים שהועלו:
//   src: "chabad" = Chabad of Greece, Kosher Products List, עדכון אוגוסט 2024
//   src: "jca"    = Kosher Hellas / Jewish Community of Athens, Kosher Restrictions for Greece
// status: certified | approved | checked | allowed_no_hashgacha | needs_hashgacha | not_authorized
// אין כל מידע שאינו מופיע במסמכים. הערות הן תרגום/תמלול נאמן בלבד.
// ====================================================================
const KOSHER_DATA = [

// ---------- GROCERY (Chabad p.03) ----------
{cat:"שמנים", name:"שמן זית כתית מעולה", brand:"מותגים שונים", status:"approved", cert:"", req:"כתית מעולה / εξαιρετικό παρθένο. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"שמנים", name:"שמן חמניות", brand:"Marata", status:"checked", cert:"", req:"נמצא בחנויות Sklavenitis. פרווה.", src:"chabad", find:"Sklavenitis"},
{cat:"מצרכים", name:"ביצים", brand:"מותגים שונים", status:"approved", cert:"", req:"עדיף ביצים בקליפה לבנה. לבדוק נקודות דם. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"טחינה", name:"טחינה (ΜΑΚΕΔΟΝΙΚΟ ΤΑΧΙΝΙ)", brand:"", status:"checked", cert:"", req:"רגילה, ללא תוספות. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"אורז", name:"אורז", brand:"מותגים שונים", status:"approved", cert:"", req:"ללא תוספות, לבדוק מחרקים. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"קוסקוס", name:"קוסקוס (רגיל / ביו)", brand:"Tipiak", status:"certified", cert:"OU", req:"סמל כשרות. פרווה. *לעיתים במדור האסייתי.", src:"chabad", find:"AB, Sklavenitis, MyMarket"},
{cat:"פסטה", name:"פסטה", brand:"Barilla", status:"approved", cert:"", req:"ללא ביצים, ללא תוספות, ללא צבע. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"פסטה", name:"פסטה", brand:"Melissa", status:"checked", cert:"", req:"רגילה, ללא תוספות, ללא צבע. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"מאפייה", name:"קמח — רגיל / תופח", brand:"מותגים שונים", status:"approved", cert:"", req:"יש לנפות. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"מאפייה", name:"אבקת סודה לשתייה", brand:"מותגים שונים", status:"approved", cert:"", req:"פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"מאפייה", name:"אבקת אפייה", brand:"מותגים שונים", status:"approved", cert:"", req:"פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"מאפייה", name:"סוכר וניל", brand:"מותגים שונים", status:"approved", cert:"", req:"פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"מאפייה", name:"קקאו", brand:"מותגים שונים", status:"approved", cert:"", req:"100% קקאו, ללא תוספות. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"ממתיקים", name:"דבש", brand:"מותגים שונים", status:"approved", cert:"", req:"100% דבש מפרחים או עשבים (לא דבש אורן או יער). פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"מצרכים", name:"מלח / סוכר", brand:"מותגים שונים", status:"approved", cert:"", req:"פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"מצרכים", name:"שומשום", brand:"מותגים שונים", status:"approved", cert:"", req:"פרווה.", src:"chabad", find:"רוב החנויות"},

// ---------- REFRIGERATED (Chabad p.04) ----------
{cat:"חלב ומוצרי חלב", name:"חלב טהור", brand:"מותגים שונים", status:"approved", cert:"", req:"ללא תוספות, לא מועשר. חלבי — חלב נוכרי.", src:"chabad", find:"רוב החנויות"},
{cat:"חמאה", name:"חמאה לא מלוחה", brand:"Lurpak", status:"certified", cert:"OK", req:"סמל מפעל DK M199 EC. חלבי — חלב נוכרי.", src:"chabad", find:"רוב החנויות"},
{cat:"חמאה", name:"חמאה לא מלוחה — לייט", brand:"Lurpak", status:"certified", cert:"OK", req:"סמל מפעל DK M199 EC. חלבי — חלב נוכרי.", src:"chabad", find:"רוב החנויות"},
{cat:"חמאה", name:"חמאה למריחה לא מלוחה", brand:"Lurpak", status:"certified", cert:"OK", req:"סמל מפעל DK M199 EC. חלבי — חלב נוכרי.", src:"chabad", find:"רוב החנויות"},
{cat:"חמאה", name:"חמאה למריחה לא מלוחה — לייט", brand:"Lurpak", status:"certified", cert:"OK", req:"סמל מפעל DK M199 EC. חלבי — חלב נוכרי.", src:"chabad", find:"רוב החנויות"},
{cat:"חמאה", name:"חמאה למריחה מלוחה", brand:"Lurpak", status:"certified", cert:"OK", req:"סמל מפעל DK M199 EC. חלבי — חלב נוכרי.", src:"chabad", find:"רוב החנויות"},
{cat:"חמאה", name:"חמאה למריחה בשמן זית", brand:"Lurpak", status:"certified", cert:"OK", req:"סמל מפעל DK M199 EC. חלבי — חלב נוכרי.", src:"chabad", find:"רוב החנויות"},
{cat:"גלידה", name:"גלידה", brand:"Haagen Dazs", status:"certified", cert:"OU", req:"סמל כשרות. חלבי — חלב נוכרי.", src:"chabad", find:"רוב החנויות"},
{cat:"גלידה", name:"גלידה", brand:"Ben & Jerry's", status:"certified", cert:"K", req:"סמל כשרות. חלבי — חלב נוכרי.", src:"chabad", find:"רוב החנויות"},
{cat:"חומוס מוכן", name:"חומוס אוריגינל", brand:"Ifantis", status:"checked", cert:"", req:"פרווה. לא בישול ישראל.", src:"chabad", find:"רוב החנויות"},
{cat:"חומוס מוכן", name:"חומוס לימון", brand:"Ifantis", status:"checked", cert:"", req:"פרווה. לא בישול ישראל.", src:"chabad", find:"רוב החנויות"},
{cat:"דגים", name:"סלמון מעושן", brand:"מותגים שונים", status:"approved", cert:"", req:"מיוצר בסקוטלנד / נורבגיה. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"דגים", name:"סלמון מעושן Scotch Choice", brand:"St. James", status:"certified", cert:"KLBD", req:"סמל כשרות. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"דגים", name:"סלמון מעושן Scotch Choice Bio", brand:"St. James", status:"certified", cert:"KLBD", req:"סמל כשרות. פרווה.", src:"chabad", find:"רוב החנויות"},

// ---------- SAUCES (Chabad p.05) ----------
{cat:"רטבים", name:"קטשופ", brand:"Heinz", status:"certified", cert:"MK", req:"קוד על הפקק כולל: TK1, TK2, TK3, TK4 או TK5. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"רטבים", name:"חרדל (Classic Yellow)", brand:"French's", status:"certified", cert:"OU", req:"סמל כשרות. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"רטבים", name:"מיונז Seriously Good", brand:"Heinz", status:"certified", cert:"COR", req:"סמל כשרות. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"רטבים", name:"מיונז Seriously Good — לייט", brand:"Heinz", status:"certified", cert:"COR", req:"סמל כשרות. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"רטבים", name:"רוטב סויה", brand:"Kikkoman", status:"certified", cert:"KLBD", req:"מיוצר בהולנד או סינגפור. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"רטבים", name:"רוטב סויה — דל מלח", brand:"Kikkoman", status:"certified", cert:"KLBD", req:"מיוצר בהולנד. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"רטבים", name:"רוטב סויה — מתוק", brand:"Kikkoman", status:"certified", cert:"KLBD", req:"מיוצר בהולנד. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"רטבים", name:"רוטב סויה Tamari — ללא גלוטן", brand:"Kikkoman", status:"certified", cert:"KLBD", req:"מיוצר בהולנד או סינגפור. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"רטבים", name:"רוטב ברביקיו Classic BBQ", brand:"Heinz", status:"certified", cert:"COR", req:"סמל כשרות. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"מרינדות", name:"מרינדה לעוף", brand:"Stubb's", status:"certified", cert:"OU", req:"סמל כשרות. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"מרינדות", name:"מרינדה לבקר", brand:"Stubb's", status:"certified", cert:"OU", req:"סמל כשרות. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"מרינדות", name:"מרינדה לחזיר (Pork)", brand:"Stubb's", status:"certified", cert:"OU", req:"סמל כשרות. פרווה. (המוצר עצמו כשר — לבדיקת המשתמש)", src:"chabad", find:"רוב החנויות"},
{cat:"ממתיקים", name:"סירופ מייפל", brand:"Vermont", status:"certified", cert:"KLBD", req:"סמל כשרות. פרווה. *לעיתים במדור הביו.", src:"chabad", find:"רוב החנויות"},
{cat:"רטבים", name:"רוטב סלט (Salad Cream)", brand:"Heinz", status:"certified", cert:"COR", req:"סמל כשרות. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"ממרחים", name:"ריבת לימון (Lemon Curd)", brand:"Tiptree", status:"certified", cert:"KLBD", req:"סמל כשרות. חלבי — חלב נוכרי.", src:"chabad", find:"רוב החנויות"},

// ---------- MILK SUBSTITUTES (Chabad p.06) ----------
{cat:"תחליפי חלב", name:"משקה שקדים — קלוי / לא ממותק", brand:"Alpro", status:"certified", cert:"Shomre Hadas Antwerp", req:"קוד אצווה מתחיל ב-2 אותיות, או מיוצר בבלגיה. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"תחליפי חלב", name:"משקה שקדים — לא קלוי / וניל", brand:"Alpro", status:"certified", cert:"Shomre Hadas Antwerp", req:"קוד אצווה מתחיל ב-2 אותיות, או מיוצר בבלגיה. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"תחליפי חלב", name:"משקה שקדים — Barista", brand:"Alpro", status:"certified", cert:"Shomre Hadas Antwerp", req:"קוד אצווה מתחיל ב-2 אותיות, או מיוצר בבלגיה. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"תחליפי חלב", name:"משקה סויה — רגיל / שוקולד", brand:"Alpro", status:"certified", cert:"Shomre Hadas Antwerp", req:"קוד אצווה מתחיל ב-2 אותיות, או מיוצר בבלגיה. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"תחליפי חלב", name:"משקה סויה — לא ממותק / וניל", brand:"Alpro", status:"certified", cert:"Shomre Hadas Antwerp", req:"מיוצר בבלגיה. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"תחליפי חלב", name:"משקה סויה — חלבון גבוה רגיל", brand:"Alpro", status:"certified", cert:"Shomre Hadas Antwerp", req:"קוד אצווה מתחיל ב-2 אותיות, או מיוצר בבלגיה. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"תחליפי חלב", name:"משקה סויה — חלבון גבוה שוקולד", brand:"Alpro", status:"certified", cert:"Shomre Hadas Antwerp", req:"קוד אצווה מתחיל ב-2 אותיות, או מיוצר בצרפת. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"תחליפי חלב", name:"משקה שיבולת שועל (Oat)", brand:"Alpro", status:"certified", cert:"Shomre Hadas Antwerp", req:"קוד אצווה מתחיל ב-2 אותיות. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"תחליפי חלב", name:"משקה שיבולת שועל — ללא סוכר / Barista", brand:"Alpro", status:"certified", cert:"Shomre Hadas Antwerp", req:"קוד אצווה מתחיל ב-2 אותיות. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"תחליפי חלב", name:"משקה שיבולת שועל ושקדים", brand:"Alpro", status:"certified", cert:"Shomre Hadas Antwerp", req:"קוד אצווה מתחיל ב-2 אותיות, או מיוצר בבלגיה. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"תחליפי חלב", name:"משקה קוקוס — ללא סוכר / שוקולד", brand:"Alpro", status:"certified", cert:"Shomre Hadas Antwerp", req:"קוד אצווה מתחיל ב-2 אותיות. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"תחליפי חלב", name:"משקה קוקוס — עם אורז", brand:"Alpro", status:"certified", cert:"Shomre Hadas Antwerp", req:"קוד אצווה מתחיל ב-2 אותיות, או מיוצר בבלגיה. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"תחליפי חלב", name:"מוצר סויה לבישול", brand:"Alpro", status:"certified", cert:"Shomre Hadas Antwerp", req:"קוד אצווה מתחיל ב-2 אותיות, או מיוצר בבלגיה. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"תחליפי חלב", name:"קינוח סויה — שוקולד / קרמל", brand:"Alpro", status:"certified", cert:"Shomre Hadas Antwerp", req:"קוד אצווה מתחיל ב-2 אותיות. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"תחליפי חלב", name:"קינוח סויה — וניל", brand:"Alpro", status:"certified", cert:"Shomre Hadas Antwerp", req:"קוד אצווה מתחיל ב-2 אותיות, או מיוצר בבלגיה. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"תחליפי חלב", name:"משקה שקדים שוקולד כהה", brand:"Alpro", status:"not_authorized", cert:"", req:"לא מאושר.", src:"chabad", find:""},

// ---------- CEREALS (Chabad p.07) ----------
{cat:"דגני בוקר", name:"Corn Flakes", brand:"Kellogg's", status:"certified", cert:"COR", req:"סמל כשרות. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"דגני בוקר", name:"All Bran Flakes", brand:"Kellogg's", status:"certified", cert:"COR", req:"סמל כשרות. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"דגני בוקר", name:"All Bran Fibre Plus", brand:"Kellogg's", status:"certified", cert:"COR", req:"סמל כשרות. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"דגני בוקר", name:"Crunchy Nut", brand:"Kellogg's", status:"certified", cert:"COR", req:"סמל כשרות. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"דגני בוקר", name:"Coco Pops", brand:"Kellogg's", status:"certified", cert:"COR", req:"סמל כשרות. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"דגני בוקר", name:"Coco Pops Chocos / Jumbos", brand:"Kellogg's", status:"certified", cert:"COR", req:"סמל כשרות. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"דגני בוקר", name:"Coco Pops Jumbos / Hazelnut", brand:"Kellogg's", status:"certified", cert:"COR", req:"סמל כשרות. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"דגני בוקר", name:"Smacks", brand:"Kellogg's", status:"certified", cert:"COR", req:"סמל כשרות. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"דגני בוקר", name:"Frosties", brand:"Kellogg's", status:"certified", cert:"COR", req:"סמל כשרות. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"דגני בוקר", name:"Miel Pops Loops", brand:"Kellogg's", status:"certified", cert:"COR", req:"סמל כשרות. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"דגני בוקר", name:"Special K", brand:"Kellogg's", status:"certified", cert:"COR", req:"סמל כשרות. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"דגני בוקר", name:"Special K — Red Fruits", brand:"Kellogg's", status:"certified", cert:"COR", req:"סמל כשרות. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"דגני בוקר", name:"Special K — Dark Chocolate", brand:"Kellogg's", status:"certified", cert:"COR", req:"סמל כשרות. חלבי — חלב נוכרי.", src:"chabad", find:"רוב החנויות"},
{cat:"דגני בוקר", name:"Weetabix Original", brand:"Weetabix", status:"certified", cert:"KLBD", req:"אין לוגו על האריזה. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"דגני בוקר", name:"Protein Crunch — אוריגינל / שוקולד", brand:"Weetabix", status:"certified", cert:"KLBD", req:"אין לוגו על האריזה. פרווה.", src:"chabad", find:"חלק מהחנויות"},
{cat:"דגני בוקר", name:"No Added Sugar (Muesli)", brand:"Alpen", status:"certified", cert:"KLBD", req:"אין לוגו על האריזה. חלבי — חלב נוכרי.", src:"chabad", find:"חלק מהחנויות"},

// ---------- MUESLI / BAKED (Chabad p.08) ----------
{cat:"דגנים ומאפים", name:"פתיתי שיבולת שועל (Oat Flakes)", brand:"מותגים שונים", status:"approved", cert:"", req:"ללא טעמים מוספים. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"דגנים ומאפים", name:"Extra — אוריגינל", brand:"Kellogg's", status:"certified", cert:"COR", req:"סמל כשרות. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"דגנים ומאפים", name:"Extra — פירות ואגוזים", brand:"Kellogg's", status:"certified", cert:"COR", req:"סמל כשרות. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"דגנים ומאפים", name:"Extra — Red Berries", brand:"Kellogg's", status:"certified", cert:"COR", req:"סמל כשרות. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"דגנים ומאפים", name:"Extra — שוקולד חלב", brand:"Kellogg's", status:"certified", cert:"COR", req:"סמל כשרות. חלבי — חלב נוכרי.", src:"chabad", find:"רוב החנויות"},
{cat:"דגנים ומאפים", name:"וופלים Caprice — רגיל", brand:"Papadopoulou", status:"checked", cert:"", req:"חלבי — חלב נוכרי, פת עכו\"ם.", src:"chabad", find:"רוב החנויות"},
{cat:"דגנים ומאפים", name:"Pure Butter Shortbread", brand:"Walkers", status:"certified", cert:"OU", req:"סמל כשרות. חלבי — חלב נוכרי, פת עכו\"ם.", src:"chabad", find:"חלק מהחנויות"},
{cat:"דגנים ומאפים", name:"לחם (רגיל, מאפייה)", brand:"", status:"not_authorized", cert:"", req:"לא מאושר — נאפה בדרך כלל באותן תבניות/תנור עם מאפים לא כשרים (עם נקניק/גבינה וכו').", src:"chabad", find:""},

// ---------- SNACKS (Chabad p.09) ----------
{cat:"חטיפים ושוקולד", name:"Dairy Milk", brand:"Cadbury's", status:"approved", cert:"KLBD", req:"אין לוגו על האריזה. חלבי — חלב נוכרי.", src:"chabad", find:"חלק מהחנויות"},
{cat:"חטיפים ושוקולד", name:"Dairy Milk — Fruit & Nut", brand:"Cadbury's", status:"approved", cert:"KLBD", req:"אין לוגו על האריזה. חלבי — חלב נוכרי.", src:"chabad", find:"חלק מהחנויות"},
{cat:"חטיפים ושוקולד", name:"Dairy Milk — Wholenut / Caramel", brand:"Cadbury's", status:"approved", cert:"KLBD", req:"אין לוגו על האריזה. חלבי — חלב נוכרי.", src:"chabad", find:"חלק מהחנויות"},
{cat:"חטיפים ושוקולד", name:"Veggie Straws (כל הטעמים)", brand:"Eat Real", status:"certified", cert:"KLBD", req:"סמל כשרות. פרווה. *לעיתים במדור הביו.", src:"chabad", find:"Kampos, Four Seasons"},
{cat:"חטיפים ושוקולד", name:"Hummus Chips (כל הטעמים)", brand:"Eat Real", status:"certified", cert:"KLBD", req:"סמל כשרות. פרווה. *לעיתים במדור הביו.", src:"chabad", find:"Kampos, Four Seasons"},
{cat:"חטיפים ושוקולד", name:"Lentil Chips (כל הטעמים)", brand:"Eat Real", status:"certified", cert:"KLBD", req:"סמל כשרות. פרווה. *לעיתים במדור הביו.", src:"chabad", find:"Kampos, Four Seasons"},
{cat:"חטיפים ושוקולד", name:"Quinoa Chips (כל הטעמים)", brand:"Eat Real", status:"certified", cert:"KLBD", req:"סמל כשרות. פרווה. *לעיתים במדור הביו.", src:"chabad", find:"Kampos, Four Seasons"},
{cat:"חטיפים ושוקולד", name:"חטיף Brazil Nut", brand:"Taste of Nature", status:"certified", cert:"OU", req:"סמל כשרות. פרווה. *לעיתים במדור הביו.", src:"chabad", find:"Kampos, Four Seasons"},
{cat:"חטיפים ושוקולד", name:"חטיף Cranberry", brand:"Taste of Nature", status:"certified", cert:"OU", req:"סמל כשרות. פרווה. *לעיתים במדור הביו.", src:"chabad", find:"Kampos, Four Seasons"},
{cat:"חטיפים ושוקולד", name:"Special K — Dark Chocolate (חטיף)", brand:"Kellogg's", status:"certified", cert:"NWK", req:"סמל כשרות. חלבי — חלב נוכרי.", src:"chabad", find:"רוב החנויות"},
{cat:"חטיפים ושוקולד", name:"Special K — Milk Chocolate (חטיף)", brand:"Kellogg's", status:"certified", cert:"NWK", req:"סמל כשרות. חלבי — חלב נוכרי.", src:"chabad", find:"רוב החנויות"},

// ---------- FRUITS & VEGETABLES (Chabad p.10) ----------
{cat:"פירות וירקות", name:"פירות טריים", brand:"הכל", status:"approved", cert:"", req:"אם מישראל — ראו הערת תרומות ומעשרות. לבדוק מחרקים. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"פירות וירקות", name:"תמרים מיובשים", brand:"מותגים שונים", status:"approved", cert:"", req:"אם מישראל — ראו הערה. לבדוק מחרקים. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"פירות וירקות", name:"שזיפים מיובשים", brand:"מותגים שונים", status:"approved", cert:"", req:"ייתכן חמץ. לבדוק מחרקים. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"פירות וירקות", name:"משמש / תאנים מיובשים", brand:"מותגים שונים", status:"approved", cert:"", req:"לבדוק מחרקים. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"פירות וירקות", name:"אגוזים גולמיים", brand:"מותגים שונים", status:"approved", cert:"", req:"גולמי בלבד (ωμά). לבדוק מחרקים. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"פירות וירקות", name:"ירקות טריים", brand:"הכל", status:"approved", cert:"", req:"אם מישראל — ראו הערה. לבדוק מחרקים. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"פירות וירקות", name:"ירקות עליים", brand:"הכל שניתן לבדיקה", status:"approved", cert:"", req:"לשטוף בסבון ולבדוק מחרקים. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"פירות וירקות", name:"קטניות יבשות", brand:"הכל", status:"approved", cert:"", req:"לבדוק מחרקים. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"פירות וירקות", name:"במיה קפואה", brand:"מותגים שונים", status:"approved", cert:"", req:"פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"פירות וירקות", name:"לבבות ארטישוק קפואים", brand:"מותגים שונים", status:"approved", cert:"", req:"פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"פירות וירקות", name:"גזר קפוא", brand:"מותגים שונים", status:"approved", cert:"", req:"פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"פירות וירקות", name:"אפונה ירוקה קפואה", brand:"מותגים שונים", status:"approved", cert:"", req:"פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"פירות וירקות", name:"שעועית ירוקה קפואה", brand:"מותגים שונים", status:"approved", cert:"", req:"פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"פירות וירקות", name:"תירס קפוא", brand:"מותגים שונים", status:"approved", cert:"", req:"פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"פירות וירקות", name:"זיתים", brand:"", status:"not_authorized", cert:"", req:"לא מאושר ללא השגחה — דורש כשרות. לעיתים מוסיפים חומץ יין לא כשר למי המלח.", src:"chabad", find:""},

// ---------- FISH list (Chabad p.11 + JCA p.7-8). דגים כשרים, שמות יווניים ----------
{cat:"דגים", name:"אנשובי / Anchovy — Gavros / Γαύρος", brand:"", status:"allowed_no_hashgacha", cert:"", req:"דג כשר (סנפיר וקשקשת). טרי או קפוא, עם מעט עור ובו קשקשים נתיקים.", src:"chabad", find:"שוק/סופר"},
{cat:"דגים", name:"Bogue — Gopa / Γόπα", brand:"", status:"allowed_no_hashgacha", cert:"", req:"דג כשר.", src:"chabad", find:"שוק/סופר"},
{cat:"דגים", name:"קרפיון / Carp — Kiprinos / Κυπρίνος", brand:"", status:"allowed_no_hashgacha", cert:"", req:"דג כשר.", src:"chabad", find:"שוק/סופר"},
{cat:"דגים", name:"דניס סלע / Common Dentex — Sinagrida / Συναγρίδα", brand:"", status:"allowed_no_hashgacha", cert:"", req:"דג כשר.", src:"chabad", find:"שוק/סופר"},
{cat:"דגים", name:"בורי / Grey Mullet — Kefalos / Κέφαλος", brand:"", status:"allowed_no_hashgacha", cert:"", req:"דג כשר.", src:"chabad", find:"שוק/סופר"},
{cat:"דגים", name:"הרינג / Herring — Renga / Ρέγγα", brand:"", status:"allowed_no_hashgacha", cert:"", req:"דג כשר.", src:"chabad", find:"שוק/סופר"},
{cat:"דגים", name:"פנדורה / Pandora — Lithrini / Λιθρίνι", brand:"", status:"allowed_no_hashgacha", cert:"", req:"דג כשר.", src:"chabad", find:"שוק/סופר"},
{cat:"דגים", name:"פרך / Perch — Perka / Πέρκα", brand:"", status:"allowed_no_hashgacha", cert:"", req:"דג כשר.", src:"chabad", find:"שוק/סופר"},
{cat:"דגים", name:"פיקרל / Picarel — Marida / Μαρίδα", brand:"", status:"allowed_no_hashgacha", cert:"", req:"דג כשר.", src:"chabad", find:"שוק/סופר"},
{cat:"דגים", name:"בורי אדום / Red Mullet — Barbuni / Μπαρμπούνι", brand:"", status:"allowed_no_hashgacha", cert:"", req:"דג כשר.", src:"chabad", find:"שוק/סופר"},
{cat:"דגים", name:"סלמון / Salmon — Solomos / Σολωμός", brand:"", status:"allowed_no_hashgacha", cert:"", req:"דג כשר. ניתן לקנות גם ללא עור בשל צבעו הייחודי.", src:"chabad", find:"שוק/סופר"},
{cat:"דגים", name:"סרדינים / Sardines — Sardela / Σαρδέλα", brand:"", status:"allowed_no_hashgacha", cert:"", req:"דג כשר.", src:"chabad", find:"שוק/סופר"},
{cat:"דגים", name:"לברק / Sea Bass — Lavraki / Λαβράκι", brand:"", status:"allowed_no_hashgacha", cert:"", req:"דג כשר.", src:"chabad", find:"שוק/סופר"},
{cat:"דגים", name:"דניס / Sea Bream — Tsipoura / Τσιπούρα", brand:"", status:"allowed_no_hashgacha", cert:"", req:"דג כשר.", src:"chabad", find:"שוק/סופר"},
{cat:"דגים", name:"סול / Sole — Glossa / Γλώσσα", brand:"", status:"allowed_no_hashgacha", cert:"", req:"דג כשר.", src:"chabad", find:"שוק/סופר"},
{cat:"דגים", name:"פורל / Trout — Pestrofa / Πέστροφα", brand:"", status:"allowed_no_hashgacha", cert:"", req:"דג כשר.", src:"chabad", find:"שוק/סופר"},
{cat:"דגים", name:"טונה / Tuna — Tonos / Τόνος", brand:"", status:"allowed_no_hashgacha", cert:"", req:"דג כשר (טרי/קפוא).", src:"chabad", find:"שוק/סופר"},
{cat:"דגים", name:"דקר לבן / White Grouper — Sfirida / Σφυρίδα", brand:"", status:"allowed_no_hashgacha", cert:"", req:"דג כשר.", src:"chabad", find:"שוק/סופר"},
{cat:"דגים", name:"מקרל / Mackerel — Kolios / Κολιός / Skoubri / Σκουμπρί", brand:"", status:"allowed_no_hashgacha", cert:"", req:"דג כשר (מ-JCA).", src:"jca", find:"שוק/סופר"},
{cat:"דגים", name:"בקלה / Cod — Bakaliaros / Μπακαλιάρος", brand:"", status:"allowed_no_hashgacha", cert:"", req:"דג כשר (מ-JCA).", src:"jca", find:"שוק/סופר"},
{cat:"דגים", name:"דניס נפוץ / Common Sea Bream — Fagri / Φαγκρί", brand:"", status:"allowed_no_hashgacha", cert:"", req:"דג כשר (מ-JCA).", src:"jca", find:"שוק/סופר"},
{cat:"דגים", name:"מאכלי ים (פירות ים)", brand:"", status:"not_authorized", cert:"", req:"לא כשר — רק דגים עם סנפיר וקשקשת.", src:"jca", find:""},
{cat:"דגים", name:"דג טחון / שניצל דגים / מוצרי דג מעובדים", brand:"", status:"needs_hashgacha", cert:"", req:"דורש השגחה רבנית.", src:"chabad", find:""},

// ---------- SPICES (Chabad p.12 + JCA). תבלינים שאינם דורשים השגחה ----------
{cat:"תבלינים", name:"בזיליקום / Basil — Βασιλικός", brand:"", status:"allowed_no_hashgacha", cert:"", req:"100% טבעי, ללא שמן, ללא תערובת.", src:"chabad", find:"רוב החנויות"},
{cat:"תבלינים", name:"עלי דפנה / Bay Leaves — Φύλλα Δάφνης", brand:"", status:"allowed_no_hashgacha", cert:"", req:"100% טבעי.", src:"chabad", find:"רוב החנויות"},
{cat:"תבלינים", name:"מסטיק כיוס טבעי / Chios Gum Mastic — Μαστίχα Χίου", brand:"", status:"allowed_no_hashgacha", cert:"", req:"טבעי בלבד (לא מוצרים שיוצרו ממנו).", src:"chabad", find:"רוב החנויות"},
{cat:"תבלינים", name:"קינמון מקלות/טחון / Cinnamon — Κανέλα", brand:"", status:"allowed_no_hashgacha", cert:"", req:"100% טבעי.", src:"chabad", find:"רוב החנויות"},
{cat:"תבלינים", name:"ציפורן שלם/טחון / Cloves — Γαρύφαλλο", brand:"", status:"allowed_no_hashgacha", cert:"", req:"100% טבעי.", src:"chabad", find:"רוב החנויות"},
{cat:"תבלינים", name:"כוסברה יבשה/טחונה / Coriander — Κόλιανδρο", brand:"", status:"allowed_no_hashgacha", cert:"", req:"100% טבעי.", src:"chabad", find:"רוב החנויות"},
{cat:"תבלינים", name:"כמון / Cumin — Κύμινο", brand:"", status:"allowed_no_hashgacha", cert:"", req:"100% טבעי.", src:"chabad", find:"רוב החנויות"},
{cat:"תבלינים", name:"שמיר / Dill — Άνιθος", brand:"", status:"allowed_no_hashgacha", cert:"", req:"100% טבעי.", src:"chabad", find:"רוב החנויות"},
{cat:"תבלינים", name:"שום טחון (לא אבקה) / Garlic Ground — Σκόρδο", brand:"", status:"allowed_no_hashgacha", cert:"", req:"טחון, לא אבקה. 100% טבעי.", src:"chabad", find:"רוב החנויות"},
{cat:"תבלינים", name:"ג'ינג'ר טחון/אבקה / Ginger — Τζίτζερ", brand:"", status:"allowed_no_hashgacha", cert:"", req:"100% טבעי.", src:"chabad", find:"רוב החנויות"},
{cat:"תבלינים", name:"פפריקה חריפה גרוסה / Hot Paprika Crushed — Μπούκοβο Καυτερό", brand:"", status:"allowed_no_hashgacha", cert:"", req:"100% טבעי, ללא שמן.", src:"chabad", find:"רוב החנויות"},
{cat:"תבלינים", name:"אגוז מוסקט / Nutmeg — Μοσχοκάρυδο", brand:"", status:"allowed_no_hashgacha", cert:"", req:"100% טבעי.", src:"chabad", find:"רוב החנויות"},
{cat:"תבלינים", name:"אורגנו / Oregano — Ρίγανη", brand:"", status:"allowed_no_hashgacha", cert:"", req:"100% טבעי.", src:"chabad", find:"רוב החנויות"},
{cat:"תבלינים", name:"פטרוזיליה / Parsley — Μαϊντανός", brand:"", status:"allowed_no_hashgacha", cert:"", req:"100% טבעי.", src:"chabad", find:"רוב החנויות"},
{cat:"תבלינים", name:"פלפל שחור / Black Pepper — Πιπέρι", brand:"", status:"allowed_no_hashgacha", cert:"", req:"100% טבעי.", src:"chabad", find:"רוב החנויות"},
{cat:"תבלינים", name:"פלפל לבן / White Pepper — Πιπέρι Λευκό", brand:"", status:"allowed_no_hashgacha", cert:"", req:"100% טבעי.", src:"chabad", find:"רוב החנויות"},
{cat:"תבלינים", name:"פימנט / Piment — Μπαχάρι", brand:"", status:"allowed_no_hashgacha", cert:"", req:"100% טבעי.", src:"chabad", find:"רוב החנויות"},
{cat:"תבלינים", name:"רוזמרין / Rosemary — Δεντρολίβανο", brand:"", status:"allowed_no_hashgacha", cert:"", req:"100% טבעי.", src:"chabad", find:"רוב החנויות"},
{cat:"תבלינים", name:"נענע / Spearmint — Δυόσμος", brand:"", status:"allowed_no_hashgacha", cert:"", req:"100% טבעי.", src:"chabad", find:"רוב החנויות"},
{cat:"תבלינים", name:"טרגון / Tarragon — Εστραγκόν", brand:"", status:"allowed_no_hashgacha", cert:"", req:"100% טבעי.", src:"chabad", find:"רוב החנויות"},
{cat:"תבלינים", name:"קורנית / Thyme — Θυμάρι", brand:"", status:"allowed_no_hashgacha", cert:"", req:"100% טבעי.", src:"chabad", find:"רוב החנויות"},
{cat:"תבלינים", name:"כורכום / Turmeric — Κουρκουμάς", brand:"", status:"allowed_no_hashgacha", cert:"", req:"100% טבעי.", src:"chabad", find:"רוב החנויות"},

// ---------- HOT & COLD BEVERAGES (Chabad p.13) ----------
{cat:"משקאות", name:"מים", brand:"הכל", status:"approved", cert:"", req:"פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"משקאות", name:"מיץ תפוזים", brand:"מותגים שונים", status:"approved", cert:"", req:"100% פרי, לבדוק רכיבים. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"משקאות", name:"מיץ רימונים", brand:"מותגים שונים", status:"approved", cert:"", req:"100% פרי, לבדוק רכיבים. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"משקאות", name:"מיץ תפוחים", brand:"מותגים שונים", status:"approved", cert:"", req:"100% פרי, לבדוק רכיבים. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"משקאות", name:"מיץ אשכוליות", brand:"מותגים שונים", status:"approved", cert:"", req:"100% פרי, לבדוק רכיבים. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"משקאות", name:"מיץ אננס", brand:"מותגים שונים", status:"approved", cert:"", req:"100% פרי, לבדוק רכיבים. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"משקאות", name:"תה ירוק — רימון / עם דבש", brand:"Arizona", status:"certified", cert:"OU", req:"סמל כשרות. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"משקאות", name:"תה קר — אפרסק / לימון", brand:"Arizona", status:"certified", cert:"OU", req:"סמל כשרות. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"משקאות", name:"תה לבן / ירוק — אוכמניות / זירו", brand:"Arizona", status:"certified", cert:"OU", req:"סמל כשרות. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"משקאות", name:"קפה", brand:"מותגים שונים (Nescafé)", status:"approved", cert:"", req:"100% ללא טעמים מוספים. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"משקאות", name:"שוקו לשתייה (Drinking Chocolate)", brand:"Cadbury's", status:"certified", cert:"KLBD", req:"אין לוגו על האריזה. פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"משקאות", name:"תה — טעמים שונים", brand:"Pukka", status:"certified", cert:"OU", req:"סמל כשרות. פרווה.", src:"chabad", find:"חלק מהחנויות"},
{cat:"משקאות", name:"תה — טעמים שונים", brand:"Dilmah", status:"certified", cert:"OU", req:"סמל כשרות. פרווה.", src:"chabad", find:"חלק מהחנויות"},
{cat:"משקאות", name:"תה — טעמים שונים", brand:"Celestial", status:"certified", cert:"OU", req:"סמל כשרות. פרווה.", src:"chabad", find:"חלק מהחנויות"},

// ---------- SOFT DRINKS (Chabad p.14) ----------
{cat:"משקאות קלים", name:"Coca Cola — רגיל / לייט", brand:"Coca Cola", status:"approved", cert:"KLBD", req:"פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"משקאות קלים", name:"Coca Cola Zero — רגיל / ללא קפאין", brand:"Coca Cola", status:"approved", cert:"KLBD", req:"פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"משקאות קלים", name:"Pepsi Blue — רגיל", brand:"Pepsi", status:"approved", cert:"KLBD", req:"פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"משקאות קלים", name:"Pepsi Max — זירו", brand:"Pepsi", status:"approved", cert:"KLBD", req:"פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"משקאות קלים", name:"Pepsi Lime — זירו", brand:"Pepsi", status:"approved", cert:"KLBD", req:"פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"משקאות קלים", name:"Sprite — רגיל / זירו", brand:"Sprite", status:"approved", cert:"KLBD", req:"פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"משקאות קלים", name:"Schweppes — Ginger Ale / Bitter Lemon", brand:"Schweppes", status:"approved", cert:"KLBD", req:"פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"משקאות קלים", name:"Schweppes — Soda Water / Tonic Water", brand:"Schweppes", status:"approved", cert:"KLBD", req:"פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"משקאות קלים", name:"7 UP — רגיל", brand:"7 UP", status:"approved", cert:"KLBD", req:"פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"משקאות קלים", name:"Fanta Orange — רגיל / זירו", brand:"Fanta", status:"approved", cert:"KLBD", req:"פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"משקאות קלים", name:"מים מוגזים", brand:"מותגים שונים (Tuborg)", status:"approved", cert:"", req:"פרווה.", src:"chabad", find:"רוב החנויות"},
{cat:"משקאות קלים", name:'משקאות "לוקס" — קולה / קולה ירוקה / לימונדה / תפוזים', brand:"Loux / λουξ", status:"certified", cert:"JCA", req:"הקהילה היהודית באתונה נותנת השגחה.", src:"jca", find:"רוב החנויות"},

// ---------- ALCOHOL (Chabad p.15 + JCA p.11) ----------
{cat:"אלכוהול", name:"בירה (ללא טעמים מוספים)", brand:"Heineken / Amstel / Stella Artois / Corona", status:"approved", cert:"", req:"מאושר ללא טעמים מוספים.", src:"chabad", find:""},
{cat:"אלכוהול", name:"בירה Mythos", brand:"Mythos", status:"checked", cert:"", req:"נבדק ואושר.", src:"chabad", find:""},
{cat:"אלכוהול", name:"ג'ין רגיל (ללא טעם, לא מענבים)", brand:"Gordon's / Tanqueray / Hendrick's / Bombay Sapphire Dry", status:"approved", cert:"", req:"רק רגיל ללא תוספות, לא מענבים/מי-גבינה/חלב.", src:"chabad", find:""},
{cat:"אלכוהול", name:"ליקר", brand:"Cointreau / Disaronno Amaretto / Drambuie / Monin Triple Sec Curacao", status:"approved", cert:"", req:"מאושר.", src:"chabad", find:""},
{cat:"אלכוהול", name:"אוזו", brand:"Ouzo Mini (EPOM) / Ouzo 12", brand2:"", status:"checked", cert:"", req:"Ouzo Mini — חברת EPOM, כתוב באותיות קטנות מאחור. (קפי KEFI מופיע ב-JCA).", src:"chabad", find:""},
{cat:"אלכוהול", name:"אוזו — KEFI", brand:"Kefi", status:"approved", cert:"", req:"מותר (מ-JCA).", src:"jca", find:""},
{cat:"אלכוהול", name:"רום (ללא טעם, לא מתובל)", brand:"Bacardi Anejo Reserva / Carta Blanca / Carta Oro", status:"approved", cert:"", req:"מאושר ללא טעם.", src:"chabad", find:""},
{cat:"אלכוהול", name:"טקילה (100% אגבה, ללא טעם)", brand:"Jose Cuervo / Patron", status:"approved", cert:"", req:"מאושר.", src:"chabad", find:""},
{cat:"אלכוהול", name:"וודקה רגילה (ללא טעם)", brand:"Absolut / Smirnoff / Grey Goose", status:"approved", cert:"", req:"מאושר.", src:"chabad", find:""},
{cat:"אלכוהול", name:"ויסקי", brand:"Johnnie Walker Black/Red / Chivas 12", status:"approved", cert:"", req:"ללא אזכור Sherry/Port/Madeira/Cognac/Dual cask/Double-matured.", src:"chabad", find:""},
{cat:"אלכוהול", name:"יין / ליקר / וודקה / ברנדי / קוניאק", brand:"", status:"needs_hashgacha", cert:"", req:"מותר רק עם השגחה. כל משקה המכיל ענבים דורש כשרות.", src:"jca", find:""},
{cat:"אלכוהול", name:"Tsipouro (טסיפורו)", brand:"", status:"not_authorized", cert:"", req:"לא כשר — עשוי מענבים.", src:"chabad", find:""},

// ---------- MISC baby formula (Chabad p.16) ----------
{cat:"שונות", name:"Neocate LCP (תמ\"ל)", brand:"Nutricia", status:"certified", cert:"KLBD", req:"בחלק מבתי המרקחת. פרווה.", src:"chabad", find:"בתי מרקחת נבחרים"},
{cat:"שונות", name:"Neocate Syneo (תמ\"ל)", brand:"Nutricia", status:"certified", cert:"KLBD", req:"בחלק מבתי המרקחת. פרווה.", src:"chabad", find:"בתי מרקחת נבחרים"},
{cat:"שונות", name:"Neocate Junior (תמ\"ל)", brand:"Nutricia", status:"certified", cert:"KLBD", req:"בחלק מבתי המרקחת. פרווה.", src:"chabad", find:"בתי מרקחת נבחרים"},

// ====================================================================
//  JCA — Kosher Hellas. הנחיות קטגוריה (הפכו למוצרים חיפושיים)
// ====================================================================
{cat:"לחם ודגנים", name:"לחם ללא שמרים (לאוכלי פת עכו\"ם)", brand:"", status:"allowed_no_hashgacha", cert:"", req:"לחם פשוט ללא תוספות; לוודא שאין שמרים; ללא שימוש דתי (צלב על האריזה); אין חשש חדש ביוון. ψωμί με προζύμι.", src:"jca", find:"מאפיות / Venetis / The Bread Factory"},
{cat:"פסטה", name:"פסטה (כללי)", brand:"Barilla / Misko", status:"allowed_no_hashgacha", cert:"", req:"רק ממותגים אלו; לוודא שאינה מכילה ביצים.", src:"jca", find:""},
{cat:"פסטה", name:"פסטה ללא גלוטן (כללי)", brand:"Barilla / Misko", status:"allowed_no_hashgacha", cert:"", req:"רק ממותגים אלו, ללא ביצים. פסטה ללא גלוטן עם סימן כשרות — בחנויות טבע.", src:"jca", find:""},
{cat:"חלב ומוצרי חלב", name:"חלב טהור פרה/עז/כבשה (לאוכלי חלב נוכרי)", brand:"Αγελαδινό / Κατσικίσιο / Πρόβειο", status:"allowed_no_hashgacha", cert:"", req:"חלב טהור בלבד (agno/Fresko, Πλήρες/Light). בקפה — לוודא חלב מסוג מותר; ללא שמנת/εβαπορέ.", src:"jca", find:""},
{cat:"חמאה", name:"חמאה (כללי — JCA)", brand:"Lurpak / Olympos", status:"allowed_no_hashgacha", cert:"", req:"מותגי החמאה המותרים.", src:"jca", find:""},
{cat:"יוגורט", name:"יוגורט מסונן 2%/5% (στραγγιστό)", brand:"Olympos", status:"allowed_no_hashgacha", cert:"", req:"יוגורט פשוט. ניתן ברוב הסופרים.", src:"jca", find:""},
{cat:"יוגורט", name:"יוגורט עיזים (κατσικίσιο)", brand:"Olympos", status:"allowed_no_hashgacha", cert:"", req:"יוגורט פשוט.", src:"jca", find:""},
{cat:"יוגורט", name:"יוגורט פרות יווני", brand:"Olympos", status:"allowed_no_hashgacha", cert:"", req:"יוגורט פשוט.", src:"jca", find:""},
{cat:"גבינות", name:"גבינת קסרי (Κασέρι)", brand:"Olympos", status:"approved", cert:"JCA", req:"באישור הקהילה היהודית של אתונה. *אין סימן כשרות על האריזה.", src:"jca", find:""},
{cat:"גבינות", name:"גבינת פטה / פטה אורגנית (Φέτα)", brand:"Olympos", status:"approved", cert:"JCA", req:"באישור JCA. *אין סימן כשרות על האריזה.", src:"jca", find:""},
{cat:"גבינות", name:"קפלוטירי (Κεφαλοτύρι) — פרה/כבשים", brand:"Olympos", status:"approved", cert:"JCA", req:"באישור JCA. *אין סימן כשרות על האריזה.", src:"jca", find:""},
{cat:"גבינות", name:"גראביירה (Γραβιέρα) — פרה/כבשים", brand:"Olympos", status:"approved", cert:"JCA", req:"באישור JCA. *אין סימן כשרות על האריזה.", src:"jca", find:""},
{cat:"גבינות", name:"אנתוטירי (Ανθότυρι)", brand:"Olympos", status:"approved", cert:"JCA", req:"באישור JCA. *אין סימן כשרות על האריזה.", src:"jca", find:""},
{cat:"גבינות", name:"מוצרלה (Μοτσαρέλα)", brand:"Olympos", status:"approved", cert:"JCA", req:"באישור JCA. *אין סימן כשרות על האריזה.", src:"jca", find:""},
{cat:"גבינות", name:"מיזיטרה (Μυζήθρα)", brand:"Olympos", status:"approved", cert:"JCA", req:"באישור JCA. *אין סימן כשרות על האריזה.", src:"jca", find:""},
{cat:"גבינות", name:"ממרח יווני — רגיל / עשבי תיבול", brand:"Olympos", status:"approved", cert:"JCA", req:"באישור JCA. *אין סימן כשרות על האריזה.", src:"jca", find:""},
{cat:"גבינות", name:"גבינה לבנה (פרה/דל שומן/ללא לקטוז/כבשים/עיזים)", brand:"Olympos", status:"approved", cert:"JCA", req:"באישור JCA. *אין סימן כשרות על האריזה.", src:"jca", find:""},
{cat:"גבינות", name:"פטה", brand:"Rousso", status:"approved", cert:"JCA", req:"באישור JCA.", src:"jca", find:""},
{cat:"גבינות", name:"גראביירה כריטיס", brand:"Graviera Kritis", status:"approved", cert:"JCA", req:"באישור JCA.", src:"jca", find:""},
{cat:"גבינות", name:"גבינה ללא תעודת כשרות", brand:"", status:"not_authorized", cert:"", req:"לא ניתן לקנות גבינות ללא תעודת כשרות.", src:"jca", find:""},
{cat:"בשר ועופות", name:"בשר ועופות", brand:"", status:"needs_hashgacha", cert:"", req:"דורש תעודת כשרות. בחורף ניתן למצוא הודו מעושן/'עוף טוב' מיובא מישראל בסופרים גדולים (AB Vasilopoulos, Sklavenitis) — לרכוש חבילה שלמה או להביא סכין אישית. לרכישה — לפנות לקהילה היהודית של אתונה.", src:"jca", find:"AB / Sklavenitis (מיובא)"},
{cat:"משקאות", name:"שייק / מיץ פירות טריים", brand:"", status:"allowed_no_hashgacha", cert:"", req:"מותר בתנאים: ללא יוגורט; ללא ענבים/מיץ ענבים; מיץ מרוכז = 100% פרי/ירק ללא חומרים משמרים ותוספות.", src:"jca", find:""},
{cat:"דגנים", name:"דגנים (כללי)", brand:"", status:"allowed_no_hashgacha", cert:"", req:"אין חשש חדש ביוון. רק דגן בלבד ללא תערובות, בצורה טבעית (יבש, לא טחון). לברור מחרקים.", src:"jca", find:""},
{cat:"קטניות", name:"קטניות יבשות (כללי)", brand:"", status:"allowed_no_hashgacha", cert:"", req:"כל הסוגים בצורה יבשה ללא כשרות. לברור מחרקים. *פסח — לברור שלוש פעמים.", src:"jca", find:""},
{cat:"אורז", name:"אורז (כללי — JCA)", brand:"", status:"allowed_no_hashgacha", cert:"", req:"מותר בצורה יבשה ללא כשרות. לברור מחרקים.", src:"jca", find:""},
{cat:"אגוזים", name:"אגוזים בקליפה / גולמיים (כללי)", brand:"", status:"allowed_no_hashgacha", cert:"", req:"מותרים בקליפה, או ללא קליפה כשידוע שטבעיים ולא קלויים (raw). לבדוק שאין קורים/כרסום/ריקבון.", src:"jca", find:""},
{cat:"פירות יבשים", name:"תאנים/תמרים/שזיפים מיובשים (ללא תוספות)", brand:"", status:"allowed_no_hashgacha", cert:"", req:"ללא תוספת סוכר/שמן/גלוקוז — ללא השגחה, לבדוק מחרקים. פירות מסוכרים/מצופים — דורשים השגחה. צימוקים/חמוציות מושרים במיץ ענבים — אסורים.", src:"jca", find:""},
{cat:"קמחים", name:"קמח חיטה/דגן (כללי)", brand:"", status:"allowed_no_hashgacha", cert:"", req:"מותר ללא כשרות בתנאי שאינו מועשר. אין חשש חדש ביוון.", src:"jca", find:""},
{cat:"קמחים", name:"קמח תירס/אורז/טפיוקה/שקדים (כללי)", brand:"", status:"allowed_no_hashgacha", cert:"", req:"מותר כשהוא קמח טהור בלבד ללא תוספים ותערובות.", src:"jca", find:""},
{cat:"קמחים", name:"קמח ללא גלוטן מקטניות (כללי)", brand:"", status:"allowed_no_hashgacha", cert:"", req:"תערובת קמחי קטניות ללא תוספים — כשר ללא השגחה. עם תוספים — לוודא שהמוצר טבעוני.", src:"jca", find:""},
{cat:"מאפייה", name:"שמרים", brand:"", status:"needs_hashgacha", cert:"", req:"לא ניתן לרכוש ללא השגחה מוכרת.", src:"jca", find:""},
{cat:"מאפייה", name:"אבקת סוכר", brand:"", status:"allowed_no_hashgacha", cert:"", req:"לוודא שמכיל סוכר בלבד ללא גלוטן/תוספים.", src:"jca", find:""},
{cat:"מאפייה", name:"תמצית וניל", brand:"", status:"needs_hashgacha", cert:"", req:"אין לרכוש ללא השגחה.", src:"jca", find:""},
{cat:"מאפייה", name:"ג'לטין", brand:"", status:"needs_hashgacha", cert:"", req:"אין לרכוש ללא השגחה.", src:"jca", find:""},
{cat:"תבלינים", name:"תבלינים (כללי — JCA)", brand:"", status:"allowed_no_hashgacha", cert:"", req:"100% מהצמח בלבד מותרים. אין לרכוש עם תוספות שמן (פפריקה), ממותקים או תערובות. עדיף לא טחונים.", src:"jca", find:""},
{cat:"רטבים", name:"רסק עגבניות", brand:"", status:"allowed_no_hashgacha", cert:"", req:"מותר ללא השגחה רק כש-100% עגבניות ללא תוספות (חומץ/שמן/צבע/טעם/ריח).", src:"jca", find:""},
{cat:"רטבים", name:"רטבים (כללי)", brand:"Heinz (נפוץ)", status:"needs_hashgacha", cert:"", req:"כל הרטבים דורשים השגחה. רבים ממוצרי HEINZ בסופרים מכילים כשרות.", src:"jca", find:""},
{cat:"טחינה", name:"טחינה גולמית (כללי)", brand:"", status:"allowed_no_hashgacha", cert:"", req:"גולמית בלבד ללא תוספות/טעמים/תבלינים. לוודא Raw Tahini ושומשום בלבד. ביוון יש גם טחינה עם השגחה.", src:"jca", find:""},
{cat:"גלידה", name:"גלידה (כללי)", brand:"", status:"needs_hashgacha", cert:"", req:"אין לרכוש ללא השגחה.", src:"jca", find:""},
{cat:"חטיפים ושוקולד", name:"מסטיק Orbit", brand:"Orbit", status:"allowed_no_hashgacha", cert:"", req:"מוחזק ככשר ללא חשש. מלבדו אין לרכוש מסטיק ללא השגחה.", src:"jca", find:""},
{cat:"חטיפים ושוקולד", name:"שוקולד Cadbury (לאוכלי חלב נוכרי)", brand:"Cadbury", status:"allowed_no_hashgacha", cert:"", req:"תוצרת אנגליה (למעט טעמי פרלין ו/או סוכריות גומי).", src:"jca", find:""},
{cat:"חטיפים ושוקולד", name:"שוקולד Toblerone (לאוכלי חלב נוכרי)", brand:"Toblerone", status:"allowed_no_hashgacha", cert:"", req:"מוחזק ככשר.", src:"jca", find:""},
{cat:"חטיפים ושוקולד", name:"שוקולד Milka (לאוכלי חלב נוכרי)", brand:"Milka", status:"allowed_no_hashgacha", cert:"", req:"תוצרת אוסטריה וגרמניה (מלבד פרלינים).", src:"jca", find:""},
{cat:"חטיפים ושוקולד", name:"שוקולד Ritter (לאוכלי חלב נוכרי)", brand:"Ritter", status:"allowed_no_hashgacha", cert:"", req:"תוצרת גרמניה בלבד.", src:"jca", find:""},
{cat:"חטיפים ושוקולד", name:"שוקולד Loacker (לאוכלי חלב נוכרי)", brand:"Loacker", status:"allowed_no_hashgacha", cert:"", req:"רק תוצרת איטליה ואוסטריה.", src:"jca", find:""},
{cat:"חטיפים ושוקולד", name:"שוקולד Lindt (לאוכלי חלב נוכרי)", brand:"Lindt", status:"allowed_no_hashgacha", cert:"", req:"ללא מילוי ליקר או אלכוהול אחר.", src:"jca", find:""},
{cat:"חטיפים ושוקולד", name:"כדורי שוקולד Mozart (לאוכלי חלב נוכרי)", brand:"Mozart", status:"allowed_no_hashgacha", cert:"", req:"למעט המכילים ליקר או אלכוהול.", src:"jca", find:""},
{cat:"חטיפים ושוקולד", name:"חטיפי Twix / Mars / Bounty / Kit-Kat (לאוכלי חלב נוכרי)", brand:"", status:"allowed_no_hashgacha", cert:"", req:"רק המיוצרים באירופה ובארה\"ב.", src:"jca", find:""},
{cat:"חטיפים ושוקולד", name:"חטיפי M&M's ו-Hershey's", brand:"", status:"not_authorized", cert:"", req:"לא ניתן לקנות, למעט אלו המיוצרים בארה\"ב ומסומנים ככשרים.", src:"jca", find:""},
{cat:"ממתיקים", name:"דבש טהור (כללי — JCA)", brand:"", status:"allowed_no_hashgacha", cert:"", req:"דבש טהור בלבד. ניתן עם תוספות טבעיות (אגוזים/פיסטוקים).", src:"jca", find:""},
{cat:"ממרחים", name:"ריבה BONNE MAMAN (מלבד ענבים)", brand:"Bonne Maman", status:"allowed_no_hashgacha", cert:"", req:"מוחזקות כמותרות, מלבד ענבים. נמכרות ביוון.", src:"jca", find:""},
{cat:"מוצרים מוגמרים/קפואים", name:"ירקות קפואים (ללא תוספות)", brand:"", status:"allowed_no_hashgacha", cert:"", req:"ירקות בלבד ללא תוספות/טעמים/תבלינים. ברוקולי/כרובית/תרד — לבדוק מחרקים (השריה 5 דק' בסבון, סינון ושטיפה). רוטב נלווה אינו כשר.", src:"jca", find:""},
{cat:"מוצרים מוגמרים/קפואים", name:"דגים קפואים (מהרשימה)", brand:"", status:"allowed_no_hashgacha", cert:"", req:"דגים כשרים מהרשימה — מותרים.", src:"jca", find:""},
{cat:"מוצרים מוגמרים/קפואים", name:"צ'יפס קפוא", brand:"", status:"needs_hashgacha", cert:"", req:"עבר בישול במפעל — אין לרכוש ללא השגחה.", src:"jca", find:""},
{cat:"שימורים", name:"שימורי ירקות/פירות (מוכרים ומזוהים)", brand:"", status:"allowed_no_hashgacha", cert:"", req:"איסור בישול נכרי לא חל על נאכלים חיים. פירות/ירקות במלח או סוכר מותרים. בחומץ — אסורים ללא השגחה.", src:"jca", find:""},
{cat:"דגים", name:"סלמון ורוד / טונה במים / טונה בשמן חמניות", brand:"John West", status:"approved", cert:"", req:"מותר (מ-JCA — מוצרי דגים משומרים).", src:"jca", find:""},
{cat:"פירות וירקות", name:"פירות וירקות חיים (כללי — JCA)", brand:"", status:"allowed_no_hashgacha", cert:"", req:"כל הפירות והירקות החיים מותרים. אם מיובאים מישראל — להפריש תרומות ומעשרות.", src:"jca", find:""},

// ====================================================================
//  JCA — טבלת מוצרים מאושרים (עמ' 21-24)
// ====================================================================
{cat:"לחם ודגנים", name:"Sprouted Wheat Bread", brand:"Natural Foods - Everfresh", status:"certified", cert:"KLBD", req:"100% חיטה מונבטת.", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"לחם ודגנים", name:"Sprouted Wheat Bread with Raisins", brand:"Natural Foods - Everfresh", status:"certified", cert:"KLBD", req:"", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"לחם ודגנים", name:"Sprouted Wheat Bread with Sunseeds", brand:"Natural Foods - Everfresh", status:"certified", cert:"KLBD", req:"", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"לחם ודגנים", name:"Sprouted Rye Bread", brand:"Natural Foods - Everfresh", status:"certified", cert:"KLBD", req:"", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"דגני בוקר", name:"Crunchy Nut (JCA)", brand:"Kellogg's", status:"certified", cert:"KLBD", req:"", src:"jca", find:"כל הסופרים"},
{cat:"דגני בוקר", name:"Coco Pops (JCA)", brand:"Kellogg's", status:"certified", cert:"KLBD", req:"", src:"jca", find:"כל הסופרים"},
{cat:"דגני בוקר", name:"Corn Flakes (JCA)", brand:"Kellogg's", status:"certified", cert:"KLBD", req:"", src:"jca", find:"כל הסופרים"},
{cat:"דגני בוקר", name:"All Bran Flakes (JCA)", brand:"Kellogg's", status:"certified", cert:"KLBD", req:"", src:"jca", find:"כל הסופרים"},
{cat:"דגני בוקר", name:"All Bran Fiber Plus (JCA)", brand:"Kellogg's", status:"certified", cert:"KLBD", req:"", src:"jca", find:"כל הסופרים"},
{cat:"לחם ודגנים", name:"Couscous", brand:"Tipiak", status:"certified", cert:"K-BDP", req:"", src:"jca", find:"AB / Sklavenitis / MyMarket"},
{cat:"קרקרים", name:"Finn Crisp Original", brand:"Finn Crisp", status:"certified", cert:"K-Finland", req:"", src:"jca", find:"AB / Sklavenitis"},
{cat:"קרקרים", name:"Finn Crisp Traditional", brand:"Finn Crisp", status:"certified", cert:"K-Finland", req:"", src:"jca", find:"AB / Sklavenitis"},
{cat:"ללא גלוטן", name:"Green Pea and Quinoa Pasta", brand:"Clearspring", status:"certified", cert:"OU", req:"", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"ללא גלוטן", name:"Corn Flakes", brand:"Freee", status:"certified", cert:"KLBD", req:"", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"ללא גלוטן", name:"Chocolate Stars", brand:"Freee", status:"certified", cert:"KLBD", req:"", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"ללא גלוטן", name:"Fibre Flakes", brand:"Freee", status:"certified", cert:"KLBD", req:"", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"ללא גלוטן", name:"Brown Rice Pasta", brand:"Freee", status:"certified", cert:"KLBD", req:"", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"ללא גלוטן", name:"Maize & Rice Pasta", brand:"Freee", status:"certified", cert:"KLBD", req:"", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"ללא גלוטן", name:"Almond Crackers (Erdmandel Schnitten)", brand:"La Pain des fleurs Blumenbrot", status:"certified", cert:"OK", req:"", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"ללא גלוטן", name:"Buckwheat Crackers (Buchweizen Schnitten)", brand:"La Pain des fleurs Blumenbrot", status:"certified", cert:"OK", req:"", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"ללא גלוטן", name:"Chestnut Crackers (Kastanien Schnitten)", brand:"La Pain des fleurs Blumenbrot", status:"certified", cert:"OK", req:"", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"ללא גלוטן", name:"Black Rice Crackers (Schwarze Reis Schnitten)", brand:"La Pain des fleurs Blumenbrot", status:"certified", cert:"OK", req:"", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"ללא גלוטן", name:"Buckwheat Noodles", brand:"Noodle Culture", status:"certified", cert:"Star-K", req:"", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"ללא גלוטן", name:"Millet and Brown Rice Noodles", brand:"Noodle Culture", status:"certified", cert:"Star-K", req:"", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"ללא גלוטן", name:"Brown Rice and Wakame Noodles", brand:"Noodle Culture", status:"certified", cert:"Star-K", req:"", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"ללא גלוטן", name:"Black Rice Noodles", brand:"Noodle Culture", status:"certified", cert:"Star-K", req:"", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"ללא גלוטן", name:"Thai Rice Noodles", brand:"Noodle Culture", status:"certified", cert:"Star-K", req:"", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"גרנולה", name:"Granola - Original", brand:"Lizi's", status:"certified", cert:"KLBD", req:"", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"גרנולה", name:"Granola - Organic", brand:"Lizi's", status:"certified", cert:"KLBD", req:"", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"גרנולה", name:"Granola - Treacle & Pecan", brand:"Lizi's", status:"certified", cert:"KLBD", req:"", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"גרנולה", name:"Granola - Low Sugar", brand:"Lizi's", status:"certified", cert:"KLBD", req:"", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"גרנולה", name:"Granola - High Protein Nuts & Seeds", brand:"Lizi's", status:"certified", cert:"KLBD", req:"", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"פסטה", name:"Pasta (JCA table)", brand:"Barilla", status:"certified", cert:"MK", req:"", src:"jca", find:"כל הסופרים"},
{cat:"חטיפים ושוקולד", name:"Quinoa Chips (כל הטעמים)", brand:"Eat Real", status:"certified", cert:"KLBD", req:"", src:"jca", find:"Kampos / Four Seasons"},
{cat:"חטיפים ושוקולד", name:"Hummus Chips (כל הטעמים)", brand:"Eat Real", status:"certified", cert:"KLBD", req:"", src:"jca", find:"Kampos / Four Seasons"},
{cat:"חטיפים ושוקולד", name:"Lentil Chips (כל הטעמים)", brand:"Eat Real", status:"certified", cert:"KLBD", req:"", src:"jca", find:"Kampos / Four Seasons"},
{cat:"חטיפים ושוקולד", name:"Veggie Straws (כל הטעמים)", brand:"Eat Real", status:"certified", cert:"KLBD", req:"", src:"jca", find:"Kampos / Four Seasons"},
{cat:"חטיפים ושוקולד", name:"Bar: Nuts & Cranberry", brand:"Ernco", status:"approved", cert:"", req:"", src:"jca", find:"Pharmacy Oggi"},
{cat:"חטיפים ושוקולד", name:"Bar: Nuts & Pistachio", brand:"Ernco", status:"approved", cert:"", req:"", src:"jca", find:"Pharmacy Oggi"},
{cat:"חטיפים ושוקולד", name:"Bar: Nuts & Honey", brand:"Ernco", status:"approved", cert:"", req:"", src:"jca", find:"Pharmacy Oggi"},
{cat:"חטיפים ושוקולד", name:"Special K: Milk Chocolate", brand:"Kellogg's", status:"certified", cert:"KLBD", req:"", src:"jca", find:"AB"},
{cat:"חטיפים ושוקולד", name:"Special K: Juicy Red Berry", brand:"Kellogg's", status:"certified", cert:"KLBD", req:"", src:"jca", find:"AB"},
{cat:"חטיפים ושוקולד", name:"Special K: Dark Chocolate & Cranberries", brand:"Kellogg's", status:"certified", cert:"KLBD", req:"", src:"jca", find:"AB"},
{cat:"חטיפים ושוקולד", name:"Organic Nut Bars", brand:"Taste of Nature", status:"certified", cert:"OU", req:"", src:"jca", find:"Kampos / Four Seasons"},
{cat:"חטיפים ושוקולד", name:"Cliff (חטיף)", brand:"Cliff", status:"certified", cert:"OU", req:"", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"חטיפים ושוקולד", name:"Barres à la grenade cranberries et framboise", brand:"Dukan", status:"certified", cert:"OU", req:"", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"חטיפים ושוקולד", name:"Bar: Maca Cranberry", brand:"Roo", status:"certified", cert:"KLBD", req:"", src:"jca", find:"Kampos / Four Seasons"},
{cat:"חטיפים ושוקולד", name:"Bar: Hemp Protein", brand:"Roo", status:"certified", cert:"KLBD", req:"", src:"jca", find:"Kampos / Four Seasons"},
{cat:"חטיפים ושוקולד", name:"Bar: Inca Berry", brand:"Roo", status:"certified", cert:"KLBD", req:"", src:"jca", find:"Kampos / Four Seasons"},
{cat:"חטיפים ושוקולד", name:"Bar: Mulberry Vanilla", brand:"Roo", status:"certified", cert:"KLBD", req:"", src:"jca", find:"Kampos / Four Seasons"},
{cat:"חטיפים ושוקולד", name:"Bar: Cacao Nibs", brand:"Roo", status:"certified", cert:"KLBD", req:"", src:"jca", find:"Kampos / Four Seasons"},
{cat:"חטיפים ושוקולד", name:"Bar: Choc Chip & Hazelnuts", brand:"Roo", status:"certified", cert:"KLBD", req:"", src:"jca", find:"Kampos / Four Seasons"},
{cat:"חטיפים ושוקולד", name:"Rookies: Date and Almond", brand:"Roo", status:"certified", cert:"KLBD", req:"", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"חטיפים ושוקולד", name:"Rookies: Apricot and Vanilla", brand:"Roo", status:"certified", cert:"KLBD", req:"", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"חטיפים ושוקולד", name:"Rookies: Choc Chip and Hazelnut", brand:"Roo", status:"certified", cert:"KLBD", req:"", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"חטיפים ושוקולד", name:"Vegan Chocolate (כל הטעמים)", brand:"iChoc", status:"certified", cert:"Triangle K - DE", req:"", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"חטיפים ושוקולד", name:"No Sugar Added Chocolate: Strawberry", brand:"No Sugar Added", status:"approved", cert:"", req:"", src:"jca", find:"Sklavenitis / AB"},
{cat:"חטיפים ושוקולד", name:"No Sugar Added Chocolate: Orange", brand:"No Sugar Added", status:"approved", cert:"", req:"", src:"jca", find:"Sklavenitis / AB"},
{cat:"חטיפים ושוקולד", name:"Chocolate (כל הטעמים)", brand:"Schogetten", status:"approved", cert:"", req:"", src:"jca", find:"Bazaar / Pharmacy Oggi / Lidl"},
{cat:"חטיפים ושוקולד", name:"Vegan Chocolate (כל הטעמים)", brand:"Vivani", status:"certified", cert:"Triangle K - DE", req:"", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"גלידה", name:"גלידה (כל הטעמים)", brand:"Ben & Jerry's", status:"certified", cert:"OU", req:"", src:"jca", find:"כל הסופרים ודוכנים"},
{cat:"גלידה", name:"גלידה (כל הטעמים)", brand:"Haagen Dazs", status:"certified", cert:"OU", req:"", src:"jca", find:"AB / Sklavenitis / OK Markets"},
{cat:"חטיפים ושוקולד", name:"Organic Lollipops", brand:"Yum Earth", status:"certified", cert:"Chaf-K", req:"פרווה.", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"תחליפי חלב", name:"Schlagcreme Vegan Spray Topping", brand:"Schlagfix", status:"certified", cert:"FK", req:"", src:"jca", find:""},
{cat:"רטבים", name:"Barbeque Sauce", brand:"Heinz", status:"certified", cert:"OU", req:"", src:"jca", find:"Supermarket Bazaar"},
{cat:"רטבים", name:"Barbeque Sauce", brand:"Mississippi", status:"certified", cert:"OU", req:"", src:"jca", find:"Supermarket MyMarket"},
{cat:"רטבים", name:"Barbeque Sauce", brand:"Sweet Baby Ray's", status:"certified", cert:"OU", req:"", src:"jca", find:"AB / Bazaar"},
{cat:"רטבים", name:"Ketchup", brand:"Heinz", status:"certified", cert:"MK", req:"", src:"jca", find:"AB / Sklavenitis"},
{cat:"ממתיקים", name:"Maple Syrup", brand:"Vermont", status:"certified", cert:"KLBD", req:"", src:"jca", find:"Supermarket AB"},
{cat:"רטבים", name:"Yellow Mustard", brand:"French's", status:"certified", cert:"OU", req:"", src:"jca", find:"כל הסופרים"},
{cat:"שמנים", name:"שמן זית", brand:"Terra Crete", status:"certified", cert:"OU", req:"", src:"jca", find:"AB / Bazaar / Sklavenitis"},
{cat:"ממרחים", name:"חמאת בוטנים (Peanut Butter)", brand:"Skippy's", status:"certified", cert:"OU", req:"", src:"jca", find:"Supermarket AB"},
{cat:"ממרחים", name:"Reese's Peanut Butter", brand:"Hershey", status:"certified", cert:"OU", req:"", src:"jca", find:"Supermarket AB"},
{cat:"רטבים", name:"Salad Dressing", brand:"Heinz", status:"certified", cert:"MK", req:"", src:"jca", find:"AB / Sklavenitis"},
{cat:"רטבים", name:"Yaemon Tamari Soya Sauce", brand:"Clearspring", status:"certified", cert:"OU", req:"", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"רטבים", name:"Shoyu Soya Sauce", brand:"Clearspring", status:"certified", cert:"OU", req:"", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"ממרחים", name:"Vegan Cocoa Spread with Hazelnuts", brand:"Sisinni Family Spreads", status:"certified", cert:"BK", req:"", src:"jca", find:"Supermarket MyMarket"},
{cat:"ממרחים", name:"Bitter Vegan Cocoa Spread", brand:"Sisinni Family Spreads", status:"certified", cert:"BK", req:"", src:"jca", find:"Supermarket MyMarket"},
{cat:"ממרחים", name:"Buono Hazelnut Spread with Milk", brand:"Sisinni Family Spreads", status:"certified", cert:"BK", req:"", src:"jca", find:"Supermarket MyMarket"},
{cat:"ממתיקים", name:"Golden Syrup - Breakfast", brand:"Lyle's", status:"certified", cert:"NWK", req:"", src:"jca", find:"Supermarket AB"},
{cat:"ממתיקים", name:"Golden Syrup - Butterscotch", brand:"Lyle's", status:"certified", cert:"NWK", req:"", src:"jca", find:"Supermarket AB"},
{cat:"רטבים", name:"Sweet White Miso", brand:"Clearspring", status:"certified", cert:"OK", req:"", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"רטבים", name:"Brown Rice Miso", brand:"Clearspring", status:"certified", cert:"OK", req:"", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"רטבים", name:"Hatcho Miso", brand:"Clearspring", status:"certified", cert:"OK", req:"", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"רטבים", name:"Barley Miso", brand:"Clearspring", status:"certified", cert:"OK", req:"", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"משקאות", name:"Iced Tea (All)", brand:"Arizona", status:"certified", cert:"OU", req:"", src:"jca", find:"AB / Bazaar / Sklavenitis"},
{cat:"מוצרי סויה", name:"Soy Vegetarian Traditional Burgers", brand:"Fry's", status:"approved", cert:"", req:"", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"מוצרי סויה", name:"Soy Vegetarian Chicken Patties", brand:"Fry's", status:"approved", cert:"", req:"", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"מוצרי סויה", name:"Soy Vegetarian Hotdogs", brand:"Fry's", status:"approved", cert:"", req:"", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"מוצרי סויה", name:"Soy Vegetarian Polony Slicing Sausage", brand:"Fry's", status:"approved", cert:"", req:"", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"מוצרי סויה", name:"Protein - Classic Plus", brand:"SunWarrior", status:"certified", cert:"OU", req:"", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"מוצרי סויה", name:"Protein - Warrior Blend", brand:"SunWarrior", status:"certified", cert:"OU", req:"", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"מוצרי סויה", name:"Protein - Classic", brand:"SunWarrior", status:"certified", cert:"OU", req:"", src:"jca", find:"Bio Supermarket: Kampos"},
{cat:"בשר ועופות", name:"Smoked Turkey (Deli)", brand:"Hod Lavan", status:"approved", cert:"", req:"", src:"jca", find:"AB / Sklavenitis"},
{cat:"פירות יבשים", name:"Dried Cranberries", brand:"Ocean Spray", status:"certified", cert:"OU", req:"", src:"jca", find:"Supermarket Bazaar"},
];

if (typeof module !== "undefined") module.exports = { KOSHER_DATA };
